#!/bin/bash

#SBATCH -n 45
#SBATCH -c 1

#SBATCH -A htc
#SBATCH -p HTC030
#SBATCH -J GyncMCMC

##SBATCH --error=job.%J.err 
#SBATCH --output=out/log/slurm%j.log

# compile modules

path=out/fac5err10
iters=100_000
thin=100
maxiters=10_000_000

echo saving to $path

export OPENBLAS_NUM_THREADS=1

echo compiling modules
srun -n1 -N1 ~/bin/htc030/julia -e \
  "using Gync;"

for s in {1..45}; do
    filename=$path/lausanne$s.jld
    srun -n1 -N1 --exclusive \
      ~/bin/htc030/julia -e  \
      "using Gync; Gync.run(\"$filename\", batchiters=$iters, maxiters=$maxiters, thin=$thin, subj=Gync.Subject(:lausanne, $s))" &
done

wait
