#!/bin/bash

#SBATCH -n 55
#SBATCH -c 1

#SBATCH -A htc
#SBATCH -p HTC030
#SBATCH -J GyncMCMC

##SBATCH --error=job.%J.err 
##SBATCH --output=job.%J.out

# compile modules
echo compiling modules
srun -n1 -N1 ~/bin/htc030/julia -e \
  "using Gync;"

path=out/factor5err5
iters=100_000

export OPENBLAS_NUM_THREADS=1


for s in {1..3}; do
  for c in {1..5}; do
    (
    filename=$path/$s\_$c.jld
    for i in {1..10}; do
      echo starting run $i for $filename
      if [ ! -e "$filename" ]; then
        srun -n1 -N1 --exclusive ~/bin/htc030/julia -e  \
          "using Gync; Gync.startmcmc($s,$iters,1,\"$filename\")" &
      else
        srun -n1 -N1 --exclusive ~/bin/htc030/julia -e  \
          "using Gync; Gync.continuemcmc(\"$filename\", $iters)" &
      fi
      wait
    done
    echo completed $filename
    )&
  done
done

wait
